# Generated by Django 3.1 on 2021-04-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFlight', '0002_auto_20210411_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=128),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
