# Generated by Django 3.1 on 2021-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainFlight', '0004_auto_20210411_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=64)),
                ('last', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passengers', to='MainFlight.Flight')),
            ],
        ),
    ]
